spring:
  application:
    name: mcp-server-postgres
  
  ai:
    mcp:
      server:
        enabled: true
        port: 3000
        
logging:
  level:
    root: INFO
    com.luanvv.mcp: DEBUG
    org.springframework.ai: DEBUG
    org.springframework.boot: INFO
    org.springframework.web: INFO
    org.springframework.jdbc: DEBUG
    org.springframework.transaction: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,loggers
  endpoint:
    health:
      show-details: always
    loggers:
      enabled: true
